name             'fieri'
maintainer       'Chef Supermarket Team'
maintainer_email 'supermarket@getchef.com'
license          'Apache 2.0'
description      'Installs/Configures fieri'
long_description 'Installs/Configures fieri'
version          '0.2.0'

depends          'apt'
depends          'brightbox-ruby'
depends          'git'
depends          'redisio'
depends          'xml'
